### ISSUE TITLE
Initial app setup

### ISSUE THREAD

**Issue by MaymoonaAlBoloshi** [MaymoonaAlBoloshi/countrify#1]
## Description 
Using Vite React set up the application and follow Vite [documentation](https://vitejs.dev/guide/) to achieve this

## UAT
- [ ] set up application with vitte
- [ ] on running `npm run dev` the app should run locally

**Comment by ireemalqarni** [comment]
hi

**Comment by MaymoonaAlBoloshi** [comment]
closed on #3
