### ISSUE TITLE
chore: cleanup and provide folder structure

### ISSUE THREAD

**Issue by MaymoonaAlBoloshi** [MaymoonaAlBoloshi/countrify#2]
## Background
clean up the project and add a proper folder structure

## UAT
- [ ] remove jsx inside of app.tsx.. add only a hello world inside of a div tag
- [ ] research and add a folder structure to the application .. provide your reasoning in the comments on why you are choosing to prepare your project this way (folder structure)

**Comment by ireemalqarni** [comment]
1. 
![Screenshot 2024-10-03 114023](https://github.com/user-attachments/assets/df97eeff-f96a-4a7f-8aed-6e3cc3bb62e9)
![Screenshot 2024-10-03 114104](https://github.com/user-attachments/assets/ccf53c29-c5f3-40c6-84d5-41e8e44d2e53)


2. Folder structure:
1. Assets Folder
This is where define your assets for your application such as image, font , even color depend on what you need in your application.
2. Components Folder
In this folder the common components that are shared within entire app. As footer folder and header.
3. Pages Folder
the pages of application which are home, about and etc... 

A well-organized folder structure simplifies navigation, supports easier scalability as the application grows, and improves team collaboration by enabling developers to work together more effectively.

**Comment by MaymoonaAlBoloshi** [comment]
@ireemalqarni this is a good start on the folder structure
Do add these folders and also cleanup the application then create a new PR
